### ISSUE TITLE
"warning: module 'Clibz' does not contain any sources."

### ISSUE THREAD

**Issue by timburks** [IBM-Swift/CZlib#1]
Is this repo currently in use?

I was hoping to use it to link `libz` into a project in a Swift Package Manager-friendly way, so I added it to my dependencies with the following (in `Package.swift`):

```
  dependencies: [
    .Package(url: "https://github.com/IBM-Swift/CZlib", Version(0,1,1)),
  ]
```

But when building with `swift build` I get this warning:

```
warning: module 'Clibz' does not contain any sources.
```

and link errors that show that `libz` wasn't linked.

```
Undefined symbols for architecture x86_64:
  "_deflate", referenced from:
      _zlib_compress in message_compress.c.o
  "_deflateEnd", referenced from:
      _zlib_compress in message_compress.c.o
  "_deflateInit2_", referenced from:
      _zlib_compress in message_compress.c.o
  "_inflate", referenced from:
      _zlib_decompress in message_compress.c.o
  "_inflateEnd", referenced from:
      _zlib_decompress in message_compress.c.o
  "_inflateInit2_", referenced from:
      _zlib_decompress in message_compress.c.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by helenmasters** [comment]
@timburks apologies that your question has sat here unanswered for such a long time.

Yes, this library is still used. It does require you to have a version of zlib installed.

I was able to add:

`.package(url: "https://github.com/IBM-Swift/CZlib.git", from: "0.1.2")` to my package dependencies 

and then 

`dependencies: ["CZlib"])`

within my `Package.swift` file on macOS and `swift build` didn't report any errors running against Swift version 4.1.

I'm closing this, as it's such an old issue, but I will add a short README to this Git repository as it might help future users.  If you have any further issues please do raise them, the fastest route to get help from the community is often via Slack http://swift-at-ibm-slack.mybluemix.net/
